### ISSUE TITLE
FizzBuzz Ruby

### ISSUE THREAD

**Issue by kayodeadeniyi** [awesome-examples/fizzbuzz#22]
Implement FizzBuzz in Ruby

**Comment by kayodeadeniyi** [comment]
Working on this

**Comment by jcxldn** [comment]
We already have a Ruby PR on #20. You can still submit a PR and it should count towards your Hacktoberfest stats (assuming you are doing that) but it may not be merged.

**Comment by kayodeadeniyi** [comment]
@Prouser123 I just checked the PR and it appears to be wrong. `fizzbuzz` will never be printed. It will only print `fizz` and `buzz`

**Comment by jcxldn** [comment]
Yeah, I'm still going through all of them as I didn't expect the sudden wave of PRs. I'll close #20 shortly.

**Comment by kayodeadeniyi** [comment]
@Prouser123 I just opened a new one here #26

**Comment by jcxldn** [comment]
Merged #26.
